### ISSUE TITLE
EvoGUI remote sensor left behind after mod removed

### ISSUE THREAD

**Issue by narc0tiq** [BenediktMagnus/Rescaled-Evolution-Factor#2]
Hi, I've noticed that [you're passing "Evolve Factor"](https://github.com/BenediktMagnus/Rescaled-Evolution-Factor/blob/master/control.lua#L86) as the `mod_name` when creating EvoGUI remote sensors.

I'm guessing you were doing this because having the actual mod name in the EvoGUI settings is _ugly_, but it also means that EvoGUI can't detect when the player removes your mod -- so the sensors get left behind with static text that has no relation to the game world.

I've got narc0tiq/EvoGUI#59 in place to change that behaviour (removing the mod name from the sensor list in the EvoGUI settings) -- once that's done, can I also ask you to send along `"Rescaled-Evolution-Factor"` as the mod_name when creating the sensors?

**Comment by BenediktMagnus** [comment]
Hello,

sorry that I let you wait so long but I was busy.

Yes, you're right, the mod passes "Evolve Factor" as mod name because it looks better that way. But if you change the behaviour I will, of course, follow you and send the real mod name.

Thanks for the note.

**Comment by narc0tiq** [comment]
No worries, mate, I haven't exactly been progressing EvoGUI myself. Good to
know we're on the same page, though.

**Comment by narc0tiq** [comment]
There we go, the EvoGUI issue is resolved and I'm pushing out v0.4.16, which will not have the crappy settings display.
